### ISSUE TITLE
Upgrade all not working

### ISSUE THREAD

**Issue by HunSpeedi** [ionic-team/vscode-extension#20]
Hi guys!

When I select the `Light Bulb` icon next to a scoped package to allow upgrading of all packages, nothing happens :confused: 
When I click on the package that should be updatable I also do not see the update button:
![image](https://user-images.githubusercontent.com/17490804/159715747-b739f8ad-0138-41f0-a309-fcd1a5d81aff.png)

Also, I do not have the `Capacitor` option to run the project on iOS, Android, etc...

Do you have any suggestions?

Thanks

```
Ionic:

   Ionic CLI                     : 6.18.1
   Ionic Framework               : @ionic/angular 6.0.8
   @angular-devkit/build-angular : 13.3.0
   @angular-devkit/schematics    : 13.3.0
   @angular/cli                  : 13.3.0
   @ionic/angular-toolkit        : 6.0.0

Capacitor:

   Capacitor CLI      : 3.4.1
   @capacitor/android : 3.4.1
   @capacitor/core    : 3.4.1
   @capacitor/ios     : 3.4.1

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   Android SDK Tools : 26.1.1 (/Users/lorandveger/Library/Android/sdk)
   NodeJS            : v14.17.5 (/Users/lorandveger/.nvm/versions/node/v14.17.5/bin/node)
   npm               : 6.14.14
   OS                : macOS Big Sur
   Xcode             : Xcode 13.1 Build version 13A1030d
```

**Comment by dtarnawsky** [comment]
Hi @HunSpeedi, let me take a look. I can see a problem with it and will get it fixed for the next release.

**Comment by HunSpeedi** [comment]
Hi @dtarnawsky, thank you very much!! :)

**Comment by dtarnawsky** [comment]
Hi @HunSpeedi , this issue is now fixed in the 1.3.2 pre-release. You can grab pre-releases from Extensions -> Ionic, choose the drop down arrow and Install Pre-Release. 1.3.2 should be out in the next few days assuming no issues reported with the pre-release.

**Comment by HunSpeedi** [comment]
Hi @dtarnawsky!
I see the upgrade all button now, but when I press it, in the output tab I see the following:
![image](https://user-images.githubusercontent.com/17490804/160228645-d180ce40-2265-4fa7-8817-cc965a40827f.png)
But after this, I would expect my package.json file to be updated, and no such thing has happened :(

Also still do not see the update button when I click on the package that should be updatable and,
I still do not have the Capacitor option to run the project on iOS, Android, etc..

**Comment by dtarnawsky** [comment]
Hi @HunSpeedi, there were a couple of additional fixes for this and now 1.4.1 is out. This should resolve the problem with the Upgrade all option. So I'll close out this issue.

For your Capacitor option: it will detect if you have the packages `cordova-android` or `cordova-ios` in your `package.json` or if you have a `cordova` section in your `package.json`. Make sure these are removed. If you are still having issues and would be willing to share your project please contact me at damian@ionic.io
