### ISSUE TITLE
Cannot run any command

### ISSUE THREAD

**Issue by rgilsimoes** [ionic-team/vscode-extension#59]
I was about to upgrade some dependencies on an existing project in which I already have been using the Ionic Extension and suddenly every command did nothing. 

In the VS Code main log window there is this constant error message: 

![image](https://user-images.githubusercontent.com/20357414/194119112-fe0d906a-54bc-4760-a915-812bce603649.png)

![image](https://user-images.githubusercontent.com/20357414/194119712-701a6af3-b767-4d60-be51-25ef7a9887fd.png)

Version: 1.71.2 (system setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by dtarnawsky** [comment]
Can you uninstall the extension. Restart VS Code, then reinstall the extension and see if the problem still exists?

**Comment by rgilsimoes** [comment]
After uninstall and restarting the behaviour continues.
I've also the same issue in MacOs.

**Comment by dtarnawsky** [comment]
It may be that VS Code's space is corrupt. Uninstalling and reinstalling VS Code will fix the issue.

**Comment by rgilsimoes** [comment]
Didn't work. Rollbacked to version 1.9.9 and it is working.

**Comment by Borongaj** [comment]
Same here, but resolved by upgrading Ionic CLI to 6.20.3.

But... same problem again since v1.10.5 extension version !

**Comment by dtarnawsky** [comment]
Hi @Borongaj, v1.10.6 was just released and contains an internal version of Ionic CLI 6.20.3 which is used if the Ionic CLI is not installed in the local project. Let's see if it gets past the issue you are seeing which may be related to the issue associated with Ionic CLI v6.20.1

**Comment by Borongaj** [comment]
Same problem with 1.10.6, sorry.

**Comment by rgilsimoes** [comment]
Upgraded VSCode, Ionic extension and all the global CLI packages and the problem persists.

**Comment by dtarnawsky** [comment]
I've tried this out with Windows 10, Intel and Silicon based macs without an issue. The error about not being able to register the command 'ionic.fix' would indicate that there is another extension with the same command name that is registered. Do you have any other ionic related extensions installed?

**Comment by Borongaj** [comment]
> Upgraded VSCode, Ionic extension and all the global CLI packages and the problem persists.

Same here, Silicon based iMac.

I had to go back to 1.9.9.

**Comment by rgilsimoes** [comment]
> I've tried this out with Windows 10, Intel and Silicon based macs without an issue. The error about not being able to register the command 'ionic.fix' would indicate that there is another extension with the same command name that is registered. Do you have any other ionic related extensions installed?

No, I've removed all of them.

**Comment by Boyownik** [comment]
I can confirm that issue. Can't run any of the options from the side-bar. Only response I get is when I click the options icon (three dots at the end of the lines of some commands). Reverting to 1.9.9 as mentioned before fixes that for me for now.

**Comment by zensystemlab** [comment]
> I can confirm that issue. Can't run any of the options from the side-bar. Only response I get is when I click the options icon (three dots at the end of the lines of some commands). Reverting to 1.9.9 as mentioned before fixes that for me for now.

How can I revert to 1.9.9?

**Comment by Borongaj** [comment]
Extension panel > Ionic extension > Extension details > Uninstall button **arrow** > Install another version.

**Comment by dtarnawsky** [comment]
A couple of questions for those on the thread:
1. Can you open VS Code fresh, go to Help -> Toggle Developer Tools, then click the Ionic extension and try to perform a command. Are there any exceptions in the console log?
2. Is anyone willing to do a zoom call to debug the issue? I may need to experiment with a couple of a few different debug versions of the extension to help work out the problem.

Sorry for the questions but I cannot repro the issue here and need a little more information to go on.

**Comment by Borongaj** [comment]
- **Since v1.12.0 and a VSCode restart, now all seems to work correctly.**

But I still can see following errors in the console log.

- Blank VSCode :

`ERR [fivethree.vscode-ionic-snippets]: Langage inconnu dans 'contributes.vscode-ionic-snippets.language'. Valeur fournie : vue-html`

- Ionic projet opened :

`Activating extension 'msjsdiag.cordova-tools' failed: command 'ionic.run' already exists.`

`[Extension Host] (node:50825) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use Code Helper --trace-deprecation ... to show where the warning was created)`

`ERR s.tmpDir is not a function: TypeError: s.tmpDir is not a function`

**Comment by zensystemlab** [comment]
> A couple of questions for those on the thread:
> 
> 1. Can you open VS Code fresh, go to Help -> Toggle Developer Tools, then click the Ionic extension and try to perform a command. Are there any exceptions in the console log?
> 2. Is anyone willing to do a zoom call to debug the issue? I may need to experiment with a couple of a few different debug versions of the extension to help work out the problem.
> 
> Sorry for the questions but I cannot repro the issue here and need a little more information to go on.

Yes, I can do a Zoom call. Now the extension works only for the new projects, but doesn't work for any existing.

**Comment by zensystemlab** [comment]
It is even stronger right now - I created new Ionic project (extension works fine), but after restart of VSCode extension doesn't work anymore. 

I see the following error in the log:

[2022-11-02 17:42:14.099] [exthost] [error] Activating extension Ionic.ionic failed due to an error:
[2022-11-02 17:42:14.099] [exthost] [error] Error: command 'ionic.run' already exists
	at n.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:109659)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:32839)
	at activate (/Users/leszekj/.vscode/extensions/ionic.ionic-1.12.0/out/extension.js:302:21)
	at Fn._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:17678)
	at Fn._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:17338)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:15133
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async E._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:8191)
	at async E._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:8133)
	at async E._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:7497)
	
and another error with reference to Ionic is this one:

[2022-11-02 17:42:20.732] [exthost] [error] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Recommendation'
    |     property 'command' -> object with constructor 'Object'
    |     property 'arguments' -> object with constructor 'Array'
    --- index 0 closes the circle
	at JSON.stringify (<anonymous>)
	(...)
        at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) ionic.runapp undefined
        
        [2022-11-02 17:44:00.621] [exthost] [error] Error: command 'ionic.fix' not found
    at S._tryExecuteCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1714:3532)
    at S.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1714:3414)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5) ionic.fix undefined

**Comment by dtarnawsky** [comment]
Looks like the extensions registered namespace of "ionic" is conflicting with other extensions like vscode-ionic-snippets.

As a resolution to this I'll go about renaming the set of commands that are registered for the extension. Stay tuned, I'll hopefully have a solution to this today...

**Comment by dtarnawsky** [comment]
Version 1.12.1 was just released and renames all registered commands from "ionic" to "ionic-official" which should resolve the issues associated with the vscode-ionic-snippets extension and any other extension that uses the name ionic.* which may have conflicted.

**Comment by rgilsimoes** [comment]
> Version 1.12.1 was just released and renames all registered commands from "ionic" to "ionic-official" which should resolve the issues associated with the vscode-ionic-snippets extension and any other extension that uses the name ionic.* which may have conflicted.

This fixed for me! Thank you @dtarnawsky!

**Comment by dtarnawsky** [comment]
Great. I'll close out this issue!
